language: java
dist: xenial
jdk:
- openjdk8
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "./test-repo"
env:
  global:
  - secure: wUjTOxBuBzlH40BXr7gQE9rPNek9qsKmUwyl30EMP2wmR1xEKn6i57gdtZNF5kALQPKx5JLTvn0OliUBZndxwcWn6pGANPDNGTeUW6p8Lc4JH1vh81mxaeVaBxxA0oBdg28RE5TutAXmOqqBV6DRiRFUMgFShdmNl+Lt+RE5VbsGMl4bokFIL0FVK+f83mko/JGYir5dUZbnOUxhGNUFldE1a1KfH2XGBtofAU7TZyoPPmxJ7FN1OHJy/b5JgUPRl0iMnCvXsXosby2tMyUbNCcKb/75FWcKtls35rEKm6ETN9oLQFEol6RrO3mSBgbKhZpFNd6FirVyPT9UecH6cH3ZOHp0WWHNrdoZCZeFw35FCUpLF01wmHXAAAArpZ+qIqSfDXO8fmSOINNUGCB8f7oEoZM8KR85pWp2eNfG49PXTnB58qNMX+GXY/DambXu6Z0l/l4wqweKjjJJBT8jFJWVPp6JaXeC5HvWOTsrpiJpYlbEZU/Y1ZlAwwEzP0k8Nj0aqgDq0CNpm6AagQxCCMXvlIQ8NZ403g95LbC3T3MgX4ji3ByvbhK51kn3XrWLASSCwOSn1ALG6/zYUBZpKMM2oeNtB6rtHcqC0hXkd4/v1TAVUMUQDGNuHuC3DsI9Ba4ABPg0rIw4IcsCb6kRxXFrDSKCco0rt4z4NK5+KEE=
  - secure: tovv4MXUjKITSC8byrLMp578r1gJ3yrHVJ23CLiQHvHUD9rKOsASqvH2qXtU0x7legzCohOQ8CujyhaJ3xOzscA/A/Oao8jQW9iHSEzhPjbMbQD3WLgavdHdiMXlTftFGg3czcrTX2+paYKAE9NEqz7TJvuK4U+GponAHY7vKhjQkOk9G+WpkbsO0rru75L7cXd+1JONTZhgp9vixy8VqByeTh/Hlai+NOpGe+PUilrFSfkSwCKfUhgIiGKa6c4iQThhvqmThJnGRINSpFK3hpmEGVvgmwiMYZE7FcYlumvmzgg27APOfoI83qoYlJB2nFyir5tQAYm/FWmxM9GVglENzGsfrr4bDC4blIa6P3uOTlsuXBdsO/QtpqdW3Tic2Lsic+5tCz4ZMncTQFYOssDB/CD76+GYABU3vuQREGyTFwqQ0Z8REcmV9ybIqsA9yqzbApDt4you9ARN65avN3zaWZo/++4BQiBs3nocCP5WhQ4o8vNcItihhoER00ZouHYlWd+PZTYDZHv99HLuqsaQ5QxmrD4l3Rs/H8/bqLaoJjJnBFnrAtbCBqEPldoDd0WR1AqoM0yEJ8JKYptU3GI9XzgcgF20Go4a6midx/D1fYOhniXksu8r5RfIsRpsgKMnmVW5k/i5D1PgRE0pynZuQogqTvszjEZNxsfvRuA=
install:
- "/bin/true"
script:
- cp -f ./.mvn/ci/settings.xml $HOME/.m2/settings.xml
- "./.mvn/verify.sh || exit 1"
- "./.mvn/release-bintray.sh || exit 1"
